#include "presence.h"
#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

void presence_config_defaults(struct presence_config *o) { o->enabled=1; o->poll_interval_seconds=5; o->show_title_id=1; o->show_content_id=1; o->discord_application_id[0]=0; }
static int key_string(const char *s,const char *key,char *out,size_t cap){char pat[64],*p;size_t n=0;snprintf(pat,sizeof(pat),"\"%s\"",key);p=strstr((char*)s,pat);if(!p)return 0;p=strchr(p+strlen(pat),':');if(!p)return -1;p++;while(*p==' '||*p=='\t')p++;if(*p++!='\"')return -1;while(*p&&*p!='\"'&&n+1<cap){if(!isdigit((unsigned char)*p))return -1;out[n++]=*p++;}out[n]=0;return *p=='\"'?1:-1;}
static int key_bool(const char *s,const char *key,int *out) { char pat[48],*p; snprintf(pat,sizeof(pat),"\"%s\"",key); p=strstr((char*)s,pat); if(!p)return 0; p=strchr(p+strlen(pat),':'); if(!p)return -1; p++; while(*p==' '||*p=='\t')p++; if(!strncmp(p,"true",4)){*out=1;return 1;} if(!strncmp(p,"false",5)){*out=0;return 1;} return -1; }
static int key_uint(const char *s,const char *key,unsigned *out) { char pat[48],*p,*end; unsigned long n; snprintf(pat,sizeof(pat),"\"%s\"",key); p=strstr((char*)s,pat); if(!p)return 0; p=strchr(p+strlen(pat),':'); if(!p)return -1; n=strtoul(p+1,&end,10); if(end==p+1 || n<3 || n>300)return -1; *out=(unsigned)n; return 1; }
int presence_config_parse(const char *json,size_t len,struct presence_config *out) { int r; if(!json||!out||len==0||len>16384||strstr(json,"token"))return -1; presence_config_defaults(out); r=key_bool(json,"enabled",&out->enabled); if(r<0)return -1; r=key_bool(json,"show_title_id",&out->show_title_id);if(r<0)return -1; r=key_bool(json,"show_content_id",&out->show_content_id);if(r<0)return -1; r=key_string(json,"discord_application_id",out->discord_application_id,sizeof(out->discord_application_id));if(r<0)return -1; return key_uint(json,"poll_interval_seconds",&out->poll_interval_seconds)<0?-1:0; }
int presence_config_serialize(const struct presence_config *c,char *o,size_t n){int r;if(!c||!o)return -1;r=snprintf(o,n,"{\n  \"enabled\": %s,\n  \"poll_interval_seconds\": %u,\n  \"show_title_id\": %s,\n  \"show_content_id\": %s,\n  \"discord_application_id\": \"%s\"\n}\n",c->enabled?"true":"false",c->poll_interval_seconds,c->show_title_id?"true":"false",c->show_content_id?"true":"false",c->discord_application_id);return r<0||(size_t)r>=n?-1:r;}
size_t presence_json_escape(const char *in,char *out,size_t cap){size_t n=0;if(!out||!cap)return 0;for(;in&&*in;in++){unsigned char c=(unsigned char)*in;char esc[8];size_t k;if(c=='"'||c=='\\'){esc[0]='\\';esc[1]=(char)c;k=2;}else if(c<0x20){snprintf(esc,sizeof(esc),"\\u%04x",c);k=6;}else{esc[0]=(char)c;k=1;}if(n+k>=cap)break;memcpy(out+n,esc,k);n+=k;}out[n]=0;return n;}
