#include "metadata.h"
#include <ctype.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

int presence_title_id_valid(const char *id) { if(!id||strlen(id)!=9)return 0; for(int i=0;i<4;i++)if(!isalpha((unsigned char)id[i]))return 0; for(int i=4;i<9;i++)if(!isdigit((unsigned char)id[i]))return 0; return 1; }
static int json_string(const char *b,const char *key,char *out,size_t cap){char n[64];const char *p;size_t i=0;snprintf(n,sizeof(n),"\"%s\"",key);p=strstr(b,n);if(!p||(p=strchr(p+strlen(n),':'))==NULL)return 0;p++;while(*p==' '||*p=='\t'||*p=='\n'||*p=='\r')p++;if(*p++!='\"')return 0;while(*p&&*p!='\"'&&i+1<cap){if(*p=='\\'&&p[1])p++;out[i++]=*p++;}out[i]=0;return i>0;}
static unsigned u16le(const unsigned char *p){return (unsigned)p[0]|((unsigned)p[1]<<8);}static unsigned u32le(const unsigned char *p){return (unsigned)p[0]|((unsigned)p[1]<<8)|((unsigned)p[2]<<16)|((unsigned)p[3]<<24);}
static int read_sfo_title(const char *path,char *out,size_t cap){unsigned char b[65536];int fd=open(path,O_RDONLY);ssize_t n;if(fd<0)return 0;n=read(fd,b,sizeof(b));close(fd);if(n<20||u32le(b)!=0x46535000)return 0;unsigned ko=u32le(b+8),doff=u32le(b+12),count=u32le(b+16);for(unsigned i=0;i<count;i++){size_t e=20+(size_t)i*16;if(e+16>(size_t)n)break;size_t kp=(size_t)ko+u16le(b+e),dp=(size_t)doff+u32le(b+e+12);unsigned len=u32le(b+e+4);if(kp>=(size_t)n||dp>=(size_t)n||len==0||dp+len>(size_t)n||strcmp((char*)b+kp,"TITLE"))continue;size_t copy=len<cap-1?len:cap-1;memcpy(out,b+dp,copy);out[copy]=0;return out[0]!=0;}return 0;}
static int read_title(const char *path,char *out,size_t cap){char b[65536];int fd=open(path,O_RDONLY);ssize_t n;if(fd<0)return 0;n=read(fd,b,sizeof(b)-1);close(fd);if(n<=0)return 0;b[n]=0;char *en=strstr(b,"\"en-US\"");if(en){char *end=strchr(en,'}');if(end){char c=*end;*end=0;if(json_string(en,"titleName",out,cap)){*end=c;return 1;}*end=c;}}return json_string(b,"titleName",out,cap);}
int presence_metadata_resolve_at(const char *root,const char *id,struct presence_metadata *o){const char *r=root?root:"";char p[320];memset(o,0,sizeof(*o));if(!presence_title_id_valid(id))return 0;snprintf(o->title_id,sizeof(o->title_id),"%s",id);const char *params[]={"%s/user/appmeta/%s/param.json","%s/user/appmeta/%s/sce_sys/param.json","%s/user/app/%s/sce_sys/param.json",NULL};for(int i=0;params[i];i++){snprintf(p,sizeof(p),params[i],r,id);if(read_title(p,o->title_name,sizeof(o->title_name)))break;}const char *sfo[]={"%s/user/appmeta/%s/param.sfo","%s/user/appmeta/%s/sce_sys/param.sfo","%s/user/app/%s/sce_sys/param.sfo",NULL};if(!o->title_name[0])for(int i=0;sfo[i];i++){snprintf(p,sizeof(p),sfo[i],r,id);if(read_sfo_title(p,o->title_name,sizeof(o->title_name)))break;}const char *icons[]={"%s/user/appmeta/%s/icon0.png","%s/user/appmeta/%s/sce_sys/icon0.png","%s/user/app/%s/sce_sys/icon0.png",NULL};struct stat st;for(int i=0;icons[i];i++){snprintf(p,sizeof(p),icons[i],r,id);if(stat(p,&st)==0&&st.st_size>0){snprintf(o->icon_path,sizeof(o->icon_path),"%s",p);break;}}return 1;}
int presence_metadata_resolve(const char *id,struct presence_metadata *o){return presence_metadata_resolve_at("",id,o);}
